---
- name: install
  hosts: test
  become_method: sudo
  become_user: root
  become: yes
  tasks:
  - name: install python3-pip
    apt:  
      name: python3-pip
      state: latest
  - name: install git
    apt:
      name: git
      state: latest
  - name: flaskex
    git:
      repo: https://github.com/anfederico/flaskex
      dest: /home/oem/flaskex
  - name: run flaskex
    shell: cd /home/oem/flaskex && pip install -r requirements.txt && python3 app.py  

