---
- name: install
  hosts: test
  become_method: sudo
  become_user: root
  
  tasks:
  - name: install python3-pip
    apt:
      name: python3-pip
      state: latest
  - name: install git
    apt:
      name: git
      state: latest
  - name: user flaskuser
    user:
      name: flaskuser
      shell: /bin/bash
  - name: flaskex
    git:
      repo: https://github.com/anfederico/flaskex
      dest: /home/flaskuser
  - name: run flaskex
    shell: cd /home/flaskuser/flaskex && pip install -r requirements.txt && python3 app.py  

